baseURL = "https://tuodominio.com/"
languageCode = "it-it"
title = "io-diego"
theme = "PaperMod"

[pagination]
  pagerSize = 10

[params]
  author = "Diego Remaggi"
  showReadingTime = true
  showCodeCopyButtons = true
  defaultTheme = "auto" # dark, light, auto
  customCSS = ["css/extra.css"]

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1

[frontmatter]
  format = "toml"